version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - ./jenkins_docker_setup.sh:/usr/local/bin/jenkins_docker_setup.sh
      - ../iac:/iac
      - ../.aws:/root/.aws
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    entrypoint: ["/bin/bash", "/usr/local/bin/jenkins_docker_setup.sh"]

volumes:
  jenkins_home:
